### ISSUE TITLE
Does Not Work at all

### ISSUE THREAD

**Issue by MarieahMannix** [Entree3k/Jellyfin#6]
Dev does not seem to understand that the Repository needs to be in place whether you are entering it under plugins or going to the link address
THERE IS NO REPOSITORY THERE
I am shouting because the dev flicks aside all attempts to tell him this
I raised this before and got the flick. I give up trying to help after this. It makes no diff to me if his work is wasted because nobody can use a plugin linked to a 404 repo

**Comment by Entree3k** [comment]
Hello,

Yes my repository https://raw.githubusercontent.com/Entree3k/Jellyfin/main/studios does 404 just like the default Emby artwork repository also 404's - https://raw.githubusercontent.com/jellyfin/emby-artwork/master/studios. This is because you do not need to actually click the link and go to it. The repository is for Jellyfin to use. You need to add the link to the studio images plugin
![plug1](https://user-images.githubusercontent.com/28127566/193420267-738dba92-57a1-493c-ba98-a9473da4c8c3.png)
![plug2](https://user-images.githubusercontent.com/28127566/193420273-d7a286f0-f68a-4e70-97aa-e4347efec20c.png)

Once you add it you need to restart Jellyfin. Then go to Shows -> TV Networks

![example 1](https://user-images.githubusercontent.com/28127566/193420297-ccdd51f6-fcbb-46f3-bc0e-e8b853a561ae.png)
![example 2](https://user-images.githubusercontent.com/28127566/193420302-7f662045-478c-4a6b-84d5-8f556e872f7d.png)
![example 3](https://user-images.githubusercontent.com/28127566/193420303-5d46ad69-dcf6-4f18-b4f1-7f5c00185492.png)
![example 4](https://user-images.githubusercontent.com/28127566/193420306-00dd177b-2b0d-4ee4-9b55-57b46d117a1e.png)

Then you should see the artwork pop up to be used for that studio image. So far the ones that are not showing up that I have noticed are Funamation, Sky Deutschland, Sky Atlantic (UK) and TV2 (NZ) which I am trying to figure out but all over's that I have tried are working. So if you have an issue with posters not showing up let me know which posters are not showing and what your Jellyfin is naming them. Since Jellyfin has different naming conventions based on your location a poster for ABC won't load for someone with ABC (US) on their server, so I need to upload a folder called ABC (US) and etc for all other posters that people have. Hope this helps you understand.
